//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraderaPublic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisementShow
    {
        public int Id { get; set; }
        public int AdvertisementId { get; set; }
        public System.DateTime Date { get; set; }
        public string Page { get; set; }
    
        public virtual Advertisement Advertisement { get; set; }
    }
}
