//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraderaPublic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combination_Technique
    {
        public int id { get; set; }
        public int combination_id { get; set; }
        public string techinque_name { get; set; }
        public Nullable<int> combination_order { get; set; }
    
        public virtual Combination Combination { get; set; }
    }
}
