//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraderaPublic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition_External_Competitor_Contact_Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competition_External_Competitor_Contact_Person()
        {
            this.Competition_External_Competitor = new HashSet<Competition_External_Competitor>();
            this.Competition_External_Competitor1 = new HashSet<Competition_External_Competitor>();
        }
    
        public int Id { get; set; }
        public int CompetitionId { get; set; }
        public string Name { get; set; }
        public string Coaches { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Club { get; set; }
        public string Message { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Competition Competition1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competition_External_Competitor> Competition_External_Competitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competition_External_Competitor> Competition_External_Competitor1 { get; set; }
    }
}
