//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraderaPublic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition_Internal_Competitor
    {
        public int Id { get; set; }
        public int CompetitionId { get; set; }
        public int AccountId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Competition Competition { get; set; }
        public virtual Competition_Category Competition_Category { get; set; }
    }
}
