//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraderaPublic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competition_Category()
        {
            this.Competition_External_Competitor = new HashSet<Competition_External_Competitor>();
            this.Competition_External_Competitor1 = new HashSet<Competition_External_Competitor>();
            this.Competition_Internal_Competitor = new HashSet<Competition_Internal_Competitor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CompetitionId { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Competition Competition1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competition_External_Competitor> Competition_External_Competitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competition_External_Competitor> Competition_External_Competitor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competition_Internal_Competitor> Competition_Internal_Competitor { get; set; }
    }
}
