//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraderaPublic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GraderaConnectionString : DbContext
    {
        public GraderaConnectionString()
            : base("name=GraderaConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Advertisement> Advertisement { get; set; }
        public virtual DbSet<AdvertisementClicks> AdvertisementClicks { get; set; }
        public virtual DbSet<Combination> Combination { get; set; }
        public virtual DbSet<Combination_Technique> Combination_Technique { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Search> Search { get; set; }
        public virtual DbSet<TECHNICS> TECHNICS { get; set; }
        public virtual DbSet<Technique> Technique { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Wordlist> Wordlist { get; set; }
        public virtual DbSet<AdvertisementShow> AdvertisementShow { get; set; }
    }
}
