//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraderaPublic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade_Category_Link
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grade_Category_Link()
        {
            this.Grade_Category_Link_Technique = new HashSet<Grade_Category_Link_Technique>();
        }
    
        public int Id { get; set; }
        public int GradeCategoryId { get; set; }
        public int GradeId { get; set; }
        public string Text { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Grade_Category Grade_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade_Category_Link_Technique> Grade_Category_Link_Technique { get; set; }
    }
}
