//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraderaPublic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade_Category_Link_Technique
    {
        public int Id { get; set; }
        public int TechniqueId { get; set; }
        public int GradeCategoryLinkId { get; set; }
        public int GradeId { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Grade_Category_Link Grade_Category_Link { get; set; }
        public virtual Technique Technique { get; set; }
    }
}
