//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraderaPublic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingExercise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingExercise()
        {
            this.TrainingExerciseLinkTechnique = new HashSet<TrainingExerciseLinkTechnique>();
        }
    
        public int Id { get; set; }
        public int ClubId { get; set; }
        public int CreatedByUser { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int AverageTime { get; set; }
        public int ExerciseType { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsGlobal { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Club Club { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingExerciseLinkTechnique> TrainingExerciseLinkTechnique { get; set; }
    }
}
