//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraderaPublic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingExerciseLinkTechnique
    {
        public int Id { get; set; }
        public int TrainingExerciseId { get; set; }
        public int TechniqueId { get; set; }
    
        public virtual Technique Technique { get; set; }
        public virtual TrainingExercise TrainingExercise { get; set; }
    }
}
