// <auto-generated />
namespace Gradera.Education.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class educationquestion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(educationquestion));
        
        string IMigrationMetadata.Id
        {
            get { return "201901191107553_education-question"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
